--DROP TABLE IF EXISTS hits; --раскомментировать для многократного прохождения тестов

CREATE TABLE IF NOT EXISTS hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        VARCHAR(64)                             NOT NULL,
    uri        VARCHAR(2000)                           NOT NULL,
    ip         VARCHAR(16)                             NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_hits PRIMARY KEY (id)
);