version: '3.1'
services:
  stats-server:
      build: ewm-stats-service/stats-server
      ports:
        - "9090:9090"
      depends_on:
        - stats-db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=admin

  stats-db:
      image: postgres:14-alpine
      container_name: db
      ports:
        - "6541:5432"
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin

  ewm-service:
    build: ewm-main-service
    container_name: ewm-main
    ports:
        - "8080:8080"
    depends_on:
        - ewm-db
        - stats-server
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-service
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=admin

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
        - "6542:5432"
    environment:
        - POSTGRES_DB=ewm-main
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
